### ISSUE TITLE
Config.ini not updated to V4 links

### ISSUE THREAD

**Issue by robby28-11** [ozdemirozcelik/pairs-ibkr#5]
Links in config.ini refer to V3:

e.g.
API_PUT_SIGNAL : http://127.0.0.1:5000/v3/webhook

**Comment by ozdemirozcelik** [comment]
I thought that keeping it as v3 was more convenient to be compatible with the tutorial video -which refers to v3 release.
But I think it is a better idea to update as v4.
Thank you for letting me know.
