### ISSUE TITLE
followed the video to create order ticker of NFLX with 100 contracts

### ISSUE THREAD

**Issue by RandyCheema** [ozdemirozcelik/pairs-ibkr#6]
JSON
{
  "rowid": "6",
  "timestamp": "2023-06-30 01:51:29",
  "ticker": "NFLX",
  "ticker1": "NFLX",
  "order_action": "buy",
  "order_contracts": "100",
  "order_price": "100",
  "mar_pos": "long",
  "mar_pos_size": "100",
  "pre_mar_pos": "long",
  "pre_mar_pos_size": "100",
  "order_status": "created",
  "order_comment": "Long(manual)",
  "status_msg": "position size mismatch",
  "passphrase": "webhook"
}

This is log file

2023-06-29 23:28:06,864 : INFO : __main__ : received signal (Equation:NFLX)
2023-06-29 23:28:06,864 : WARNING : __main__ : order positions mismatch
2023-06-29 23:28:07,018 : INFO : __main__ : order information (position size mismatch) updated for rowid:6

**Comment by ozdemirozcelik** [comment]
To prevent order duplication and mismatches, several filters are in place before sending orders to IBKR. Regarding order size, the market position (after the order is executed) should satisfy the following condition:
mar_pos_size = pre_mar_pos_size + order_contracts

For the above case, it doesn't satisfy the requirement:
100 (long) ≠ 100 (long) + 100(buy)
